* GNOWSYS Studio
    GNOWSYS Studio (gStudio for short) is an online platform for collaboration that supports 
    maintaining electronic publishing and curation of resources (online file management), 
    online discussion, content management, group and task management, event management, 
    create and play online courses, information management, semantically link all published resources,
    visualize graphs, analytics, user rating etc. 
    
    The platform is best suited for a collaborative online academy. 
    
    The platform is still under active development. Some of the apps of the platform are
    being used for http://nroer.gov.in/ (of CIET, NCERT) http://studio.tiss.edu/ (of NUSSD TISS) and 
    http://www.metaStudio.org/ by the gnowledge lab.
    
    Gnowledge lab of Homi Bhabha Centre for Science Education, TIFR develops and 
    maintains gStudio as its flagship software development project for supporting online education.

* Design of the Platform

    The platform is designed around Users, Groups and Apps to construct knowledge. 

** Users
    As a platform for collaboration, the most essential resource is a group of users called *collaborators*. 
    All that the users need to join the platform is an email address.  
    
    Each user is provided with a workspace to create resources of various kinds. 
    See below about the kind of resources users can create using special Apps.
    
** Groups
    A group is a virtual workspace for collaboration among a group of users. It is 
    possible to create public or private groups which can be moderated or not.
    
    A parent group may have one more more sub-groups.
    
    Users of a group can create resources of various kinds withint the workspace of the group. 
    See below about the kind of resources users can create using special Apps.
    
    Gruop members are always a subset of the registered users of the platform.
    
    Two kinds of groups are possible within the platform. 
    - *Special Interest Groups*: A group whose activities are typically unscheduled 
        and will last as long as the group members continue to collaborate.
    - *Program Event Groups*: A group whose activities are scheduled and members are 
        enrolled for the purpose it is created. They typically start at a scheduled time 
        and will end when the event is closed. 
    
** Apps
    Several Apps are provided in the platform for use within the user's workspace 
    as well as the groups' workspace to collaboratively 
    constuct knowledge.  More and more Apps are bieng  developed.  
    The platform supports the following Apps for the first release to happen by August 2015:
    - Pages and collection of Pages for collaboratively writing documents
    - File and collection of Files (any file generated by any computer can be uploaded 
        and managed including images, videos, sound files, word processing files, PDFs, HTML files and so on.)
    - Forum for discussion integrated with a mailing list 
    - Blog pages and collection of Blogs (under development)
    - Knowledge Organizer for maintaining a taxonomy of digital resources into themes and topics.
    - Semantic Knowledge Networking to establish named linkages between topics and concepts
    - Task manager for the gruop as well as the users
    - Event Scheduler 
    - Observation reporting based on time and location
    - Course Designer 
    - Course Player
    - Information Manager 
    - Email Client
    - Local Messages
    - Notifications
    - Meetings
    - Quiz Builder 
